version: "3.3"

services:
    nginx:
        build: ./srcs/nginx
        ports:
            - 443:443
        networks: 
            - inception-network
        volumes: 
            - wp-files:/wordpress
        depends_on:
            - wordpress

    wordpress:
        build: ./srcs/wordpress
        networks: 
            - inception-network
        volumes:
            - wp-files:/wordpress
        depends_on:
            - mariadb

    mariadb:
        build: ./srcs/mariadb
        networks: 
            - inception-network
        volumes:
            - db-files:/var/lib/mysql

networks:
    inception-network:
        driver: bridge

volumes:
    wp-files:
    db-files: