version: "3.3"
services:
    web:
        build: ./nginx
        ports:
            - "443:443"
        networks: 
            - default
        volumes: 
            - first:/wordpress
    wordpress:
        build: ./Wp+php
        networks: 
            - default
        volumes: 
            - first:/wordpress
networks:
    default:
volumes:
    first: